"""Added JournalTransaction model

Revision ID: 2a2341f54102
Revises: 4ef692d69faa
Create Date: 2023-09-07 21:42:55.788263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2341f54102'
down_revision = '4ef692d69faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
